[web]
port = 8080 # The port the website will listen to.
url = "http://localhost:8080" # Do not add / at last. Change it to a proper domain for it to properly work. Ex: https://agentntfy.vercel.app

[login]
userAgent = "" # Set your customized user-agent (security) here and set it in your browser as well. This is the only way to access the panel.

[deception]
redirect = "https://www.youtube.com/watch?v=dQw4w9WgXcQ" # Default is Rickroll.

[database] # MongoDB
clusterURL = "" # Your database cluster URL with the credential.
database = "" # The name of the database where the collection is located.
agentsCollection = "" # The name of the collection where agents are stored.
messagesCollection = "" # The name of the collection where messages are stored.